- method: "proxy"
  arguments:
    proxied: "IMA-B 5 P2"
    base: "IMA-B 5"

- method: "proxy"
  arguments:
    proxied: "IRF-M P2"
    base: "IRF-M"

- method: "spread"
  arguments:
    spreaded: "IPCA"

- method: "regress"
  arguments:
    regressed: "Darius"
    base: "Zarathustra"

- method: "regress"
  arguments:
    regressed: "Sigma"
    base: "Axis"

- method: "mix"
  arguments:
    mixed: "IMA ex-S"
    base:
    - "IMA-B"
    - "IRF-M"

- method: "mix"
  arguments:
    mixed: "Giant"
    base:
    - "Darius"
    - "Sigma"
