- name: "Risk Free Rate"
  benchmark: "IPCA"
  assets:
    - "CDI"
    - "SELIC"
  simulate_portfolio: False

- name: "Equity: Capitalization"
  benchmark: "CDI"
  assets:
    - "IBrX 50"
    - "IBOV"
    - "IBrX 100"
    - "IBrA"
  simulate_portfolio: False

- name: "Equity: Governance"
  benchmark: "CDI"
  assets:
    - "IGC"
    - "IGCT"
  simulate_portfolio: False

- name: "Equity: Dividend"
  benchmark: "CDI"
  assets:
    - "IDIV"
  simulate_portfolio: False

- name: "Equity"
  benchmark: "CDI"
  assets:
    - "IBrA"
    - "IGC"
    - "IDIV"
  simulate_portfolio: False

- name: "Bond"
  benchmark: "CDI"
  assets:
    - "IMA"
    - "IMA-S"
    - "IMA-B"
    - "IRF-M"
    - "IMA ex-S"
  simulate_portfolio: False

- name: "REIT"
  benchmark: "CDI"
  assets:
    - "IFIX L"
    - "IFIX"
  simulate_portfolio: False

- name: "Multi-Asset: Giant"
  benchmark: "CDI"
  assets:
    - "Sigma"
    - "Darius"
    - "Giant"
  simulate_portfolio: False

- name: "Equity + Bond"
  benchmark: "CDI"
  assets:
    - "IBrA"
    - "IMA"
  simulate_portfolio: True

- name: "Equity + Bond + REIT"
  benchmark: "CDI"
  assets:
    - "IBrA"
    - "IMA"
    - "IFIX"
  simulate_portfolio: True

- name: "Equity + Bond + REIT + Multi-Asset"
  benchmark: "CDI"
  assets:
    - "IBrA"
    - "IMA"
    - "IFIX"
    - "Giant"
  simulate_portfolio: True

- name: "Equity + Bond: Alternative"
  benchmark: "CDI"
  assets:
    - "IGC"
    - "IMA ex-S"
  simulate_portfolio: True

- name: "Equity + Bond + REIT: Alternative"
  benchmark: "CDI"
  assets:
    - "IGC"
    - "IMA ex-S"
    - "IFIX"
  simulate_portfolio: True

- name: "Equity + Bond + REIT + Multi-Asset: Alternative"
  benchmark: "CDI"
  assets:
    - "IGC"
    - "IMA ex-S"
    - "IFIX"
    - "Giant"
  simulate_portfolio: True
